travis:
  secure:
    BINSTAR_TOKEN: 1sc0ZeBD6F9EqsRQIsQs4sDkYJMdpVd5Avp0C7gckwRISeTnJI12l0L/nnEZmA0qXo1TzUTiWnjdc/el/X8/Wm3bZnK90du58aJ2JafpWvjLm5Qk1xMIMeMNjNNIOw4dVpuT/w8eMHlYl047ZOBnsr69KRmNVW9fwBikZ5Sry1liMjT3I4JANAx/BUp+wuLfxSTOMToajwiBjFOmaOBuCAYe98PvtfXkXraI0M4UJNgw6j08uASl8YmHajt0Nxx6ojyPh0Jd34D7dEI/Yom2mcl3W/RhbLdfYSucomJiDs0YJhUbDT0Z9QFD11evHD0nkqhWpxx/BR/j6Rr/7raevLba5kTwqOWGv28F3k1yvykcKDYt0YFZfDfmdaE+OkxH8X82tRBZrx5pgku4dLFVn92IuGsSj2rSul/pwzQbkY3ZMFIDIiZnVatRP71FNrOetDclRsDCDPN9ngOCWdokJZyRgKrNHpzkTVkHQVCC0VMivL5fp+sYgKXEfMYFcBimAVFo1vPetmViSB0i3IbzhYsTtvRIj5aTpEhfXppFnfKzlN1ptq8P4WWuTcG7fp93AMUvgnxogSz+mxRIWUkGhVKVFa+0oQqZmr2sakQedW7PJPs99BxnJHjIBY/m4mWbmaEWkqXXvvQ9L5u4a2+xoQbJXFLFw/vk42imQS4qYzk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
